name: FastAPI CI/CD

on:
  workflow_dispatch:


jobs:

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install pre-commit
        run: pip3 install pre-commit
      - name: run pre-commit
        run: pre-commit run --all-files

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install python dependencies
        run: |
          pip3 install -r requirements.txt
          pip3 install -r tests/requirements.txt
      - name: Run Tests
        run: pytest

  Build-artifacts:
    needs: [tests, pre-commit]
    runs-on: ubuntu-latest
    outputs:
      file_hash1: ${{ steps.create-package.outputs.file_hash }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: create zip package
        id: create-package
        env:
          file_hash: ${{ hashFiles('api/**', 'requirements.txt') }}
        run: |
          pip3 install -r requirements.txt --target dependencies
          cd ./dependencies && zip -r9 ../$file_hash .
          # add API files to Zip file
          cd ../api && zip -g ../$file_hash -r .

          echo "file_hash=$file_hash" >> $GITHUB_OUTPUT
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1.0.4
        with:
          version: 2
      - name: Upload to S3
        run: aws s3 cp $file_hash.zip s3://fastapi-artifacts/$file_hash.zip
        env:
          file_hash: ${{ hashFiles('api/**', 'requirements.txt') }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1

  CD:
    runs-on: ubuntu-latest
    needs: [Build-artifacts]
    # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Deploy new Lambda
        run: aws lambda update-function-code --function-name fastapi --s3-bucket fastapi-artifacts --s3-key ${{needs.Build-artifacts.outputs.file_hash1}}.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1
