name: Terraform
on:
  workflow_dispatch:
  push:

jobs:
  terraform:
    name: Terraform apply
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Terraform setup
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - run: yes yes
      - name: Initialize S3 Backend
        run: |
          mkdir migration && cd migration
          cat > migration.tf <<EOL
          terraform {
            backend "s3" {
              bucket = "fastapi-tf-bucket"
              key    = "infra/terraform.tfstate"
              region = "eu-west-1"
            }
          }
          EOL
          terraform init

      - name: Initialize TFE Backend
        run: |
          cd migration
          cat > migration.tf <<EOL
          terraform {
            cloud {
              organization = "bialik-magdalena"
              workspaces {
                name = "aws-fastapi2"
              }
            }
          }
          EOL
          printf "yes" | terraform init
